### ISSUE TITLE
希望增加自定义短链的功能

### ISSUE THREAD

**Issue by 7noemo** [fuingzu/ShortUrl#3]
目前是只能随机字符串，希望加一个支持自定义的。谢谢。

**Comment by fuingzu** [comment]
感谢建议。
目前有一个大的新版本还在测试，整个后端都被我重构了，大概今明两天可以更新。
新版本会有这些功能

**Comment by fuingzu** [comment]
新项目已发，这个项目有您所需要的功能。
https://github.com/fuingzu/Magic-Link
